EWL-8512: Full Width Index Page Membership Promos
AmericanMedicalAssociation/ama-style-guide-2 pull request #1005
Opened 2021-02-24 17:43 UTC by plibby

## Ticket(s)

**Github Issue**
N/A

**Jira Ticket**
- [EWL-8512: Index: Mobile, Membership Custom Block - Make Full Width](https://issues.ama-assn.org/browse/EWL-8512)

## Description
Added index-page specific change to membership promo blocks to remove padding and margins (making them full width) in accordance to [Zeplin](https://zpl.io/anqwggn) and acceptance criteria.

**Broke out the parent selectors and re-targeted based on "category" and "subcategory" index template selectors to address inconsistency in QA testing.**

## To Test
- [ ] Pull branch
- [ ] Link styleguide (run `lando link-styleguides`
- [ ] Run `lando gulp` from `styleguide`
- [ ] Navigate to an Index page and verify that the membership promo block is now full width. Compare and critique with [Zeplin](https://zpl.io/anqwggn).

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
![Screenshot_2021-02-11 Access to Health Care Coverage](https://user-images.githubusercontent.com/57365587/107666383-162c8080-6c54-11eb-8741-98c713bc1c8e.png)

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2021-03-04 22:38 UTC, Dr-Zee requested changes
padding rule is causing overflow and some horizontal scroll.
![Screen Shot 2021-03-04 at 4 37 57 PM](https://user-images.githubusercontent.com/10862145/110040248-175b4580-7d08-11eb-8535-33be04910316.png)

2021-03-15 19:10 UTC, alexmartinez92 commented
There was a syntax error in the media query this update made, fixed that and its looking good. New commit is in.

2021-03-16 15:21 UTC, caharder approved these changes
Looks good. horizontal scroll is gone.

2021-03-16 16:06 UTC, Dr-Zee approved these changes

2021-03-16 16:19 UTC, merged