EWL-8552: Vertical trending block style adjustments.
AmericanMedicalAssociation/ama-style-guide-2 pull request #1038
Opened 2021-05-20 16:00 UTC by alexmartinez92

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- N/A

**Jira Ticket**
- [EWL-8552: Trending module on AMAone homepage](https://issues.ama-assn.org/browse/EWL-8552)

## Description
Adjust header spacing and view all trending link styling.

## To Test
- Link styleguides locally
- If not present, follow instructions here to create/place a vertical trending block on the homepage: [https://github.com/AmericanMedicalAssociation/ama-d8/pull/2640](https://github.com/AmericanMedicalAssociation/ama-d8/pull/2640)
- Confirm spacing between purple header bar and first article is 14px.
- Confirm spacing above and below "View all Trending" cta is 14px.

## Visual Regressions
- N/A

## Relevant Screenshots/GIFs
- N/A

## Remaining Tasks
- N/A

## Additional Notes
- N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2021-05-21 19:30 UTC, Dr-Zee requested changes
It looks like the 14px padding rule is being overridden by a 15px padding rule inside the container.
![Screen Shot 2021-05-21 at 2 27 11 PM](https://user-images.githubusercontent.com/10862145/119188997-130a1300-ba41-11eb-9709-21720b76dae7.png)

2021-05-21 19:41 UTC, alexmartinez92 commented
That rule is true for the horizontal block, but the class is not present on the vertical block.
![Screen Shot 2021-05-21 at 2 41 18 PM](https://user-images.githubusercontent.com/67962801/119190174-a0019c00-ba42-11eb-8a48-c407ecd3d95e.png)

2021-05-25 21:49 UTC, caharder approved these changes

2021-05-25 21:50 UTC, Dr-Zee approved these changes

2021-05-25 21:54 UTC, merged