EWL-8884: subcat read more android tablet fix.
AmericanMedicalAssociation/ama-style-guide-2 pull request #1051
Opened 2021-07-01 15:12 UTC by alexmartinez92

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- N/A

**Jira Ticket**
- [EWL-8884: Subcat Video Custom Block | Read More does not show up on Android_Tablet ](https://issues.ama-assn.org/browse/EWL-8884)

## Description
Adjusted height of truncated text section for a closed 'Read More' section on tablet width Subcategory pages.

## To Test
-  Run 'lando link-styleguides' to get latest
-  Confirm 'Read More' button on Subcat pages appears on tablet sized devices (ex: http://ama-one.lndo.site/about/ama-career-opportunities)

## Visual Regressions
- N/A

## Relevant Screenshots/GIFs
- N/A

## Remaining Tasks
- N/A

## Additional Notes
- N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2021-07-02 15:54 UTC, Dr-Zee requested changes
At some widths, fix is causing the link to be hidden.
![Screen Shot 2021-07-02 at 10 53 37 AM](https://user-images.githubusercontent.com/10862145/124300155-dba08300-db23-11eb-993e-ebcfde27fe06.png)

2021-07-02 20:03 UTC, alexmartinez92 commented
@Dr-Zee can you retest this one? There was another PR merged in which tweaked the Read More settings and it may have fixed this, the latest from dev is merged in. Have not been able to reproduce the error with the latest.

2021-07-08 21:34 UTC, plibby approved these changes

2021-07-08 21:48 UTC, Dr-Zee approved these changes

2021-07-08 21:48 UTC, merged