EWL-9228: Adds styling for gutter between link columns.
AmericanMedicalAssociation/ama-style-guide-2 pull request #1146
Opened 2022-02-08 17:07 UTC by alexmartinez92

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- n/a

**Jira Ticket**
- [EWL-9228: Home Page Annual Interim custom block | adjust desktop gutter width](https://issues.ama-assn.org/browse/EWL-9228)

## Description
Adds styling to add gutter spacing between meeting link columns.

## To Test
- Checkout the corresponding ama-d8 PR
- link styles locally
- Navigate to annual interim block on homepage
- Confirm gutter between meeting link columns exists and matches the following (only on desktop) [Zeplin](https://app.zeplin.io/project/5da0e00b85f67a23e567b630/screen/61e9d9e9930a4eb59d5f822a)

## Visual Regressions
- N/A

## Relevant Screenshots/GIFs
![Screen Shot 2022-02-08 at 11 01 57 AM](https://user-images.githubusercontent.com/67962801/153038589-ce9bc304-9c20-46bd-9382-a88f994ed87d.png)

## Remaining Tasks
- N/A

## Additional Notes
- N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2022-02-10 15:58 UTC, joshuathorne approved these changes

2022-02-10 16:03 UTC, joshuathorne requested changes
Gutter affects links but not column headers.

2022-02-10 19:26 UTC, alexmartinez92 commented
@joshuathorne a new commit is in, should now balance out header and link column gutter, as well as account for shorter header copy.

2022-02-14 19:10 UTC, joshuathorne approved these changes

2022-02-14 19:10 UTC, merged