EWL-9201: Adjust alert banner styling for tablet.
AmericanMedicalAssociation/ama-style-guide-2 pull request #1158
Opened 2022-02-22 21:53 UTC by alexmartinez92

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- n/a

**Jira Ticket**
- [EWL-XXXX: Ticket Title](https://issues.ama-assn.org/browse/EWL-XXXX)

## Description
Adjusts styling for alert banner to accommodate tablet styling.

## To Test
- **NOTE** There is a pr in here to update the critical css for alert banner, check with this PR pulled or delete the critical css from the head tag when reviewing. (open console, find <style id="critical-css"></style> and delete)
- Link styleguide locally
- create new test banner
- confirm styling matches the following zeplins:
[Desktop](https://zpl.io/2pqDWmJ)

[Tablet](https://zpl.io/VD358vJ)

[Mobile](https://zpl.io/adoBnDe)

## Visual Regressions
-n/a

## Relevant Screenshots/GIFs
- n/a

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
**NOTE** There is a pr in here to update the critical css for alert banner, check with this PR pulled!!

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2022-02-22 23:43 UTC, joshuathorne requested changes
@alexmartinez92  I'm seeing then in tablet display 
![Screenshot 2022-02-22 173953](https://user-images.githubusercontent.com/10862145/155238503-071e6d30-25c7-4a92-be26-42433de680af.jpg)

2022-02-23 15:56 UTC, alexmartinez92 commented
@joshuathorne please check again, and see the note in the instructions above. the critical css from before was causing the error, the other pr referenced (now merged in to develop) resolves the issue. 

With the latest you will have to run the critical css scripts locally. In a terminal run the following three commands in the root:
lando critical desktop menu
lando critical mobile menu
lando critical desktop menu add_ons

then clear caches and check again.

2022-02-23 19:25 UTC, joshuathorne requested changes
I'm still seeing the issue
![Screenshot 2022-02-23 132500](https://user-images.githubusercontent.com/10862145/155392912-850c9930-8c1d-477c-93c4-68b43d5939fd.jpg)

2022-02-23 20:25 UTC, joshuathorne approved these changes

2022-02-23 20:25 UTC, merged