EWL-10922: Hide Social Icons from Cat/Subcat Pages
AmericanMedicalAssociation/ama-style-guide-2 pull request #1720
Opened 2024-08-23 20:11 UTC by kegraves

# Pre-PR Checklist
If you have access to approved developer tools such as AMA co-pilot, ask it the following and test any suggestions before posting the PR.
- [ ] Make this code secure.
- [ ] Make this code null and empty safe.
- [ ] Make this functionality accessible.
- [ ] Make this code more efficient.
- [ ] Beautify this code and comment it with lines above, not inline, that are no longer than 80 chars.

**Jira Ticket**
- [EWL-XXXX: Ticket Title](https://issues.ama-assn.org/browse/EWL-XXXX)

## Description
Explain the technical implementation of the work done.

## To Test
- Add detailed steps for reviewers to test this feature.

## Visual Regressions
Ensure any available regression testing has been run.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks

## Additional Notes
Anything more to add?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2024-09-03 18:33 UTC, caharder requested changes, later dismissed
@kegraves The icons still show up when you scroll on mobile, but they should never appear on mobile. This is on both cat and subcat. Looks great otherwise :)
![image](https://github.com/user-attachments/assets/f992dce3-d723-4d85-b01b-6734ded4fb6b)

2024-09-04 17:21 UTC, kegraves commented
@caharder Adjusted JS.  Ready for re-review.

2024-09-09 17:51 UTC, joshuathorne approved these changes

2024-09-09 17:52 UTC, joshuathorne approved these changes

2024-10-04 03:23 UTC, merged