[EWL-4866] SG2 | Broken Markup for Tools Block on Topic Page
AmericanMedicalAssociation/ama-style-guide-2 pull request #175
Opened 2018-04-16 20:43 UTC by JaeBea

## Ticket(s)

**Jira Ticket**
- [EWL-4866 SG2 | Broken Markup for Tools Block on Topic Page](https://issues.ama-assn.org/browse/EWL-4866)

## Description

The tools block on any topic page should render with a h5 heading tag and class "ama__h5". Currently on `develop` the tools block heading and learn more heading shows broken HTML. The heading renders as `<h>` (https://americanmedicalassociation.github.io/ama-style-guide-2/?p=pages-topic).

This update corrects the broken markup by defining "level" and "class" in the topic page json for heading atoms related to the tools block. Backstop.json has been updated to reference the correct wrapper dive for tools block. This will ensure any regression is found during tests for this block.

## To Test
- [ ] Pull `develop` branch.
- [ ] Run `gulp serve` to load style guide.
- [ ] Go to http://localhost:3000/?p=pages-topic.
- [ ] Inspect heading element for Tools block to see broken heading markup.
- [ ] Pull `feature/EWL-4866-broken-markup-tools-block` branch.
- [ ] Run `gulp serve` to load style guide.
- [ ] Go to http://localhost:3000/?p=pages-topic.
- [ ] Observe updated tools block headings. You may inspect element to see fixed HTML.

## Visual Regressions

Only 6 fails occur when running `backstop test`. These failures are from a difference in exact date specified on "membership" molecules and the tool block reference images . Those new reference images have been committed with this PR.

## Relevant Screenshots/GIFs

**Broken HTML Headers**
<img width="237" alt="screenshot-topicpage-toolsheaders" src="https://user-images.githubusercontent.com/4438120/38833998-b621c8b6-418c-11e8-88e4-ce11dd3c9778.png">

**Fixed HTML Headers**
<img width="246" alt="screenshot-topicpage-toolsheaders-fixed" src="https://user-images.githubusercontent.com/4438120/38834011-bd8f0f96-418c-11e8-8ca1-1cfd2f30999d.png">

## Remaining Tasks

N/A

## Additional Notes

- Ticket needs to be created to address missing backstop reference images for other molecules/organisms that show "not found" during test.

---

2018-04-18 16:04 UTC, labbydev commented
@JaeBea how is this related to PR #165 they both seem to be doing the same thing? (or at least similar things).

2018-04-18 16:27 UTC, JaeBea commented
@labbydev The PR you noted updated the tools organism to have h5 headings in SG2 and d8.

This update adds missing attributes to the json for the topics page tool organism as only part of the attributes for the header atom were defined. The partially defined attributes seemed to have caused the markup to be broken on SG2 only. I have added another screenshot to clarify what was going on in the html.

2018-04-19 22:18 UTC, mrspete commented
@JaeBea please resolve the conflicts and resubmit.  Thanks!

2018-04-23 18:27 UTC, JaeBea commented
@mrspete and @labbydev merge conflict seems to be resolved.

2018-04-24 16:20 UTC, labbydev requested changes
Please _only include_ the code that is relevant to this specific ticket. 

`README`, `standards`, `package.json`, `date-block.json`, `date-block.twig`, `article-stub.twig`, `promo.twig`, `lead-news.json`, `lead-news.twig`, `masthead.json`, `masthead.twig`, `news.json`,  `press-release.json`, `style-guide-welcome.json`, `style-guide-welcome.twig`, `topic.json`, `wayfinder.js`, `_unordered-list.scss`, `_lead-news.scss`, `_promo.scss`, `_ribbon-dropdown.scss`, `_tool.scss`, `_ribbon.scss` updates that are not specific to this ticket should _not_ be included in this PR.

2018-04-24 16:20 UTC, labbydev commented on styleguide/source/assets/scss/01-atoms/_unordered-list.scss
> +    @include gutter($margin-left-full...);
This specifically is causing a number of issues in D8 and making things like the admin menu and the IPE look broken. 

<img width="1058" alt="screen shot 2018-04-24 at 11 07 25 am" src="https://user-images.githubusercontent.com/1653723/39200233-32fe7896-47b1-11e8-9534-be57aeea16da.png">

2018-05-08 18:29 UTC, JaeBea commented
After discussion with team this PR will be closed.

2018-05-08 18:30 UTC, closed without merging