EWL-4909: Add textarea atom
AmericanMedicalAssociation/ama-style-guide-2 pull request #195
Opened 2018-04-24 19:08 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-4896: SG2 | Create "textarea atom](https://issues.ama-assn.org/browse/EWL-4896)

## Description
Create input field atom.

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=atoms-textarea
- [ ] Observe label that says LABEL
- [ ] Observe an texarea with "Text area" for a placeholder
- [ ] Observe the counter under the textarea aligned right
- [ ] Observe when entering characters in the textarea the counter subtracting the character count
- [ ] Observe when exceeding the 150 character limit the textarea border is red along with the the counter text being red
- [ ] Observe when the character count is below the threshold of 150 characters the red border and red counter turning back to the default colors 

## Visual Regressions
backstop test only noted the footer organism as failures due to it shifting positions.

## Relevant Screenshots/GIFs
<img width="1277" alt="screen shot 2018-04-24 at 2 08 23 pm" src="https://user-images.githubusercontent.com/2271747/39208596-1298e5b0-47c9-11e8-9795-58a8b1c5f2a0.png">

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-04-26 16:22 UTC, labbydev reviewed
This looks good but I'm not seeing the word count behavior as noted in the Zeplin. We may want to leave this out of the prototype if it's going to be handled with a Drupal module.

2018-04-26 16:22 UTC, labbydev commented on styleguide/source/assets/js/form-items.js
> +          }
<img width="265" alt="screen shot 2018-04-26 at 11 22 46 am" src="https://user-images.githubusercontent.com/1653723/39318616-34b9b4ea-4944-11e8-8e43-049a3c0b33c6.png">


None of this is appearing in PatternLab, also since this will likely be using the [Maxlength module](https://www.drupal.org/project/maxlength) or something similar we probably just want to fake it in the styleguide and not add the extra CSS. We should confirm this with @Brian-Clement or @mrspete.

2018-04-26 16:34 UTC, designerneil commented on styleguide/source/assets/js/form-items.js
> +          }
@toph asked for the character count.

2018-04-26 16:40 UTC, labbydev commented on styleguide/source/assets/js/form-items.js
> +          }
Ok, then it's still not showing up for me.

2018-04-26 17:36 UTC, designerneil commented on styleguide/source/assets/js/form-items.js
> +          }
It's there. Look all the way to the right of your screen

2018-04-27 18:49 UTC, nstriedinger requested changes

2018-04-27 18:49 UTC, nstriedinger commented on styleguide/source/assets/js/form-items.js
> +            if(max_length < character_entered) {
Add a space after keyword "if"

2018-04-27 18:56 UTC, nstriedinger commented
@designerneil Should these form elements be 100% width to fill out their container?

2018-04-27 19:14 UTC, nstriedinger approved these changes

2018-04-27 19:14 UTC, merged