EWL-4912 radio button
AmericanMedicalAssociation/ama-style-guide-2 pull request #202
Opened 2018-04-25 20:34 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-4912: SG2 | Update checkbox atom](https://issues.ama-assn.org/browse/EWL-4912)

## Description
Adds checkbox atom

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=atoms-radio-button
- [ ] Observe a group of radio buttons with a label Year Medical Student
- [ ] Click on any of the radio buttons
- [ ] Observe the radio is purple with a purple border

## Visual Regressions

backstop test. No failures

## Relevant Screenshots/GIFs
<img width="255" alt="screen shot 2018-04-25 at 3 34 27 pm" src="https://user-images.githubusercontent.com/2271747/39271262-29bbe546-489e-11e8-8a77-5be5259aa74e.png">

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-04-26 16:18 UTC, labbydev requested changes
Similar to others I'm seeing some discrepancies between the Zeplin and PatternLab:
* Label should be all caps and light gray
* option labels should be a dark gray color
* Circles are getting cut off when selected

**Pattern Lab**
<img width="200" alt="screen shot 2018-04-26 at 11 01 20 am" src="https://user-images.githubusercontent.com/1653723/39318368-91fa8ff4-4943-11e8-9994-5cf3047d3689.png">

**Zeplin**
<img width="229" alt="screen shot 2018-04-26 at 11 18 42 am" src="https://user-images.githubusercontent.com/1653723/39318391-9df5bc48-4943-11e8-89c5-2f4ca84223c4.png">

2018-04-26 17:54 UTC, labbydev approved these changes

2018-04-26 17:54 UTC, labbydev commented
Updates look good just need to resolve the merge conflicts

2018-04-27 19:34 UTC, nstriedinger commented
This doesn't have the purple ring around it like the Zeplin screenshot?

![screen shot 2018-04-27 at 3 32 59 pm](https://user-images.githubusercontent.com/231467/39381506-5f75f1ca-4a30-11e8-95db-d3f7b2f940c4.png)

2018-04-27 19:47 UTC, merged