EWL-5294 category page article stub organism
AmericanMedicalAssociation/ama-style-guide-2 pull request #300
Opened 2018-06-20 20:30 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-5294 SG2 | Create "Category Page Article Stub Four-Up/Three-Up" Organism (Cat/Subcat)](https://issues.ama-assn.org/browse/EWL-5294)

## Description
Create category page article stub with four up on desktop, two up on tablet and full size on mobile

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=organisms-category-page-article-stub
- [ ] observe 4 article stubs in a row with images, subcategory headers and headers
- [ ] resize your viewport to tablet size
- [ ] observe the article stubs stack in two columns
- [ ] resize your browser to phone size
- [ ] observe the article stubs stack in one column (note: the change here was approved by the UX team)
- [ ] Did you test in IE 11? yes

## Visual Regressions

Add category page article stub organism test
Note: The article stub for category page has been altered. The left and right padding has been removed

## Relevant Screenshots/GIFs
<img width="1312" alt="screen shot 2018-06-20 at 3 29 31 pm" src="https://user-images.githubusercontent.com/2271747/41682914-c2393b80-749e-11e8-8807-2ff9eb629b23.png">

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-06-20 23:26 UTC, labbydev requested changes
It looks like some of the responsive styling doesn't match up with the Zeplin files. Specifically, they should still be 4-up on tablet. Also the images should be on the left on mobile instead of on top.

<img width="245" alt="screen shot 2018-06-20 at 6 20 07 pm" src="https://user-images.githubusercontent.com/1653723/41689693-7b77e840-74b7-11e8-814a-6e27b816c728.png">

2018-06-20 23:26 UTC, labbydev commented on styleguide/source/_patterns/03-organisms/category-page-article-stub.twig
> +  {% set contentGroupingHeader = categoryArticleStub.contentGroupingHeader %}
This should be optional

2018-06-20 23:26 UTC, labbydev commented on styleguide/source/_patterns/03-organisms/category-page-article-stub.json
> +    "articleStubs": [
I'd like to see at least one example here that includes the metadata if not more.

2018-06-20 23:26 UTC, labbydev commented on styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
> +      width: 47%;
According to the zeplin files these should still be 4-up on tablet. 
<img width="581" alt="screen shot 2018-06-20 at 6 20 18 pm" src="https://user-images.githubusercontent.com/1653723/41689665-4a265330-74b7-11e8-991f-356434617103.png">

2018-06-21 21:17 UTC, designerneil commented on styleguide/source/_patterns/03-organisms/category-page-article-stub.twig
> +  {% set contentGroupingHeader = categoryArticleStub.contentGroupingHeader %}
@labbydev during my UX collab session I asked them about the left and right and convinced them not to change it on mobile devices

2018-06-21 21:18 UTC, designerneil commented on styleguide/source/_patterns/03-organisms/category-page-article-stub.twig
> +  {% set contentGroupingHeader = categoryArticleStub.contentGroupingHeader %}
I'll show Toph the current implementation and see if he approves.

2018-06-22 15:07 UTC, designerneil commented
@labbydev 
the the metadata has been added
the content grouping header is now optional
as the for the amount of tiles that show. UX is aware of the implementation in this PR. They have agreed the number of tiles showing should depend on the size of the container and not a fixed number.

2018-06-22 18:06 UTC, labbydev approved these changes

2018-06-22 18:06 UTC, merged