EWL-5303 - Fix overflow issue in IE 11 and view all not working correctly
AmericanMedicalAssociation/ama-style-guide-2 pull request #311
Opened 2018-06-28 14:32 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-5303: Ticket Title](https://issues.ama-assn.org/browse/EWL-5303)

## Description

- View all button doesn't work correctly. When a user clicks on it the view all doesn't change text to view less
- The organism overflow is showing in IE 11

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=organisms-subcategory-exploration-as-with-images
- [ ] click view all
- [ ] observe the view turns into view less and more subcategories appear
- [ ] click view less
- [ ] observe fewer categories show and the text turns to view more
- [ ] visit http://localhost:3000/?p=organisms-subcategory-exploration-as-with-images using browserstack https://www.browserstack.com/
- [ ] Test the website in IE11
- [ ] observe that the row does not appear outside of the container
- [ ] Did you test in IE 11? Yes

## Visual Regressions

Because of of slight width and padding changes due to making this organism work in IE11 organism backstop ref needed to get updated. This affected all pages that used this organism. Those page backstop refs also have been updated.

## Relevant Screenshots/GIFs
<img width="1209" alt="screen shot 2018-06-28 at 9 32 01 am" src="https://user-images.githubusercontent.com/2271747/42040816-227fa192-7ab6-11e8-9391-0e3f444079bb.png">
<img width="1222" alt="screen shot 2018-06-28 at 9 32 15 am" src="https://user-images.githubusercontent.com/2271747/42040830-2b7bcab4-7ab6-11e8-8f00-6e6d2d10f38f.png">

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-06-28 14:51 UTC, labbydev commented
@designerneil is this `ready for review`?

2018-07-05 17:16 UTC, labbydev requested changes
@designerneil this all looks good but I'm continuing to get backstop failures with this component, can you please check backstop and confirm that things are correct?

2018-07-06 02:41 UTC, designerneil commented
@labbydev I've fixed the backstop test. You should be good to go now.

2018-07-06 16:14 UTC, labbydev approved these changes

2018-07-06 16:14 UTC, merged