Feature/ewl 5386 people listing page
AmericanMedicalAssociation/ama-style-guide-2 pull request #317
Opened 2018-07-03 15:52 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- EWL-5386: SG2 | Create People Listing Page (Grid view only) Finalized Version](https://issues.ama-assn.org/browse/EWL-5386)

## Description
Add people listing page with people listing cards and masthead

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=pages-people-listing
- [ ] observe a masthead with two rows with 4 columns of cards
- [ ] resize your browser to tablet size
- [ ] observe three rows with 2 columns of cards 
- [ ] resize your browser to mobile size
- [ ] observe the cards are single stacked 
- [ ] Did you test in IE 11?

## Visual Regressions
updated backstop test by adding people listing page 
added all people listing backstop image refs

## Relevant Screenshots/GIFs
<img width="1203" alt="screen shot 2018-07-03 at 10 51 20 am" src="https://user-images.githubusercontent.com/2271747/42230619-0bfe0c86-7eaf-11e8-85fc-ca4885fd152a.png">
<img width="283" alt="screen shot 2018-07-03 at 10 51 51 am" src="https://user-images.githubusercontent.com/2271747/42230647-1cb55b74-7eaf-11e8-95d1-57df6b758693.png">
<img width="826" alt="screen shot 2018-07-03 at 10 51 45 am" src="https://user-images.githubusercontent.com/2271747/42230648-1cc6a762-7eaf-11e8-9082-60dd30eb2296.png">

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-07-05 22:07 UTC, labbydev requested changes
None of the conflict of interest links include the download icon as dictated in the Zeplin. 

Some of the the items should show without full content so that we can test how they appear with different amounts of vertical content.

None of the items include the "View Full Profile" button some should and some should not so that we can test both ways. 

There do not seem to be backstop reference images for just the card pattern.

Please include the ticket and the testing instructions for any sub patterns as well.

2018-07-05 22:07 UTC, labbydev commented on styleguide/source/_patterns/05-pages/people-listing.json
> +      "date": {
There should not be a date on the masthead of this page.

2018-07-06 04:30 UTC, designerneil commented
@labbydev I don't understand what you mean by "Please include the ticket and the testing instructions for any sub patterns as well."

2018-07-06 17:18 UTC, labbydev commented
@designerneil what I mean, is that you are including code to create the sub patterns (the cards on the listing) in this PR that are not included in develop. However, you do not indicate that this PR is dependent on any other PR, nor do you include testing instructions or notes for those patterns.

2018-07-06 19:06 UTC, designerneil commented
@labbydev the sub patterns testing instructions are included in PR#

EWL-5411 Add people listing page stub #313
https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/313

EWL-5289 Add two column right full width #320 
https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/320

EWL-5402 Create "People Listing" Molecule and CTA variant #314
https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/314

2018-07-06 21:59 UTC, labbydev approved these changes

2018-07-06 21:59 UTC, merged