[EWL-5533] SG2 | Add icon element stying for "Link Icons"
AmericanMedicalAssociation/ama-style-guide-2 pull request #351
Opened 2018-07-18 18:57 UTC by JaeBea

## Ticket(s)

**Jira Ticket**
- [EWL-5533: SG2 | Add icon element stying for "Link Icons"](https://issues.ama-assn.org/browse/EWL-5533)

## Description
As a developer, I should be able to use the `<icon>` element with relevant classes on Link Icon atoms just as it is used on tool icons.

## To Test
- Pull `bug/EWL-5533-style-icon-element-link-icon` branch
- Run gulp serve in ama-style-guide-2/styleguide to ensure a local version of style guide is running.
- This work is used in code from ama-d8 [PR #581](https://github.com/AmericanMedicalAssociation/ama-d8/pull/581) so you may need to edit your local provision var to point to a local version of the D8 `feature/EWL-5106-resource-related-links-tab-theming` branch to test.
-In your local d8 project folder, run `vagrant ssh`, `drush @one.local cim -y`, and `drush @one.local cr` to import new config files and flush all caches ensuring theme recognizes updated templates.
- Navigate to any resource page and add related links tab content as a content editor would.
- View updated page and confirm icons show as they do on the [style guide resource page](https://americanmedicalassociation.github.io/ama-style-guide-2/)

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bug/EWL-5533-style-icon-element-link-icon/html_report/index.html).

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
### This PR must be merged for [PR #581](https://github.com/AmericanMedicalAssociation/ama-d8/pull/581) to be merged.
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-07-18 22:47 UTC, labbydev requested changes
@JaeBea just a quick comment on this, we should ticket this todo and remove the comment.

2018-07-18 22:47 UTC, labbydev commented on styleguide/source/assets/scss/01-atoms/_links.scss
> +// TODO: All link icon atoms should switch to using the <icon> element with appropriate class instead of hard coding the svg file
@JaeBea has this todo been ticketed? This is something we likely either want to log as tech debt or add to the backlog to fix post-launch.

2018-07-19 14:27 UTC, JaeBea commented on styleguide/source/assets/scss/01-atoms/_links.scss
> +// TODO: All link icon atoms should switch to using the <icon> element with appropriate class instead of hard coding the svg file
@labbydev, I have removed the comments and created a bug ticket,  [EWL-5571: SG2 | Standardize on use of icon element](https://issues.ama-assn.org/browse/EWL-5571)

2018-07-19 15:27 UTC, labbydev approved these changes

2018-07-19 15:27 UTC, merged