EWL-5790 | Add Header and Footer to all Pages
AmericanMedicalAssociation/ama-style-guide-2 pull request #387
Opened 2018-08-15 21:26 UTC by designerneil

**Jira Ticket**
- [EWL-5790: Ticket Title](https://issues.ama-assn.org/browse/EWL-5790)

## Description
Add header and footer to all pages

## To Test
- [ ] gulp serve
- [ ] observe the following pages now have a header and footer:

- http://localhost:3000/?p=pages-news-as-gated
- http://localhost:3000/?p=pages-news-with-jama-examples
- http://localhost:3000/?p=pages-news
- http://localhost:3000/?p=pages-category
- http://localhost:3000/?p=pages-error
- http://localhost:3000/?p=pages-event-listing
- http://localhost:3000/?p=pages-event
- http://localhost:3000/?p=pages-hub
- http://localhost:3000/?p=pages-people-bio
- http://localhost:3000/?p=pages-people-listing
- http://localhost:3000/?p=pages-press-release
- http://localhost:3000/?p=pages-resource
- http://localhost:3000/?p=pages-subcategory
- http://localhost:3000/?p=pages-topic

- [ ] Did you test in IE 11?

## Visual Regressions

## Relevant Screenshots/GIFs
![screencapture-localhost-3000-patterns-05-pages-topic-05-pages-topic-html-2018-08-15-16_25_50](https://user-images.githubusercontent.com/2271747/44174195-e9f61000-a0a7-11e8-81c9-dbd1dbea633f.png)

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-08-20 19:50 UTC, labbydev requested changes
* The Homepage is still missing the Main Navigation
* The resource page is having an overflow issue with the tab content 
![screen shot 2018-08-20 at 2 51 39 pm](https://user-images.githubusercontent.com/1653723/44363055-9cebb280-a488-11e8-8851-01e5bf126ca0.png)
* There is an extra bracket around the Main navigation in at least the press release page 
![screen shot 2018-08-20 at 2 52 45 pm](https://user-images.githubusercontent.com/1653723/44363115-c3a9e900-a488-11e8-8e8d-80ae6b8e4260.png)

2018-09-04 19:59 UTC, labbydev commented
Missing the Main Navigation on the Search Results page.

2018-09-04 21:21 UTC, designerneil commented
@labbydev I didn't even know the search results page was done. Kudos for finishing that up. I have added the header to that page.

2018-09-04 21:40 UTC, labbydev approved these changes

2018-09-04 21:43 UTC, merged