EW:-5821: Homepage promo link styling.
AmericanMedicalAssociation/ama-style-guide-2 pull request #415
Opened 2018-09-19 17:18 UTC by damontgomery

## Ticket(s)
**Jira Ticket**
- [EWL-5821: A1 | Homepage Promos block theming](https://issues.ama-assn.org/browse/EWL-5821)

## Description
The anchor tags are needed to provide a link, but they did not inherit the button styling. The style guide only shows a button and not a contained anchor.

## To Test
- This should not impact any existing styling.
- Go to /ama-style-guide-2/?p=pages-homepage

## Visual Regressions

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5821-homepage-promo-links/html_report/index.html).

## Relevant Screenshots/GIFs

Example from styleguide which will not change appearance.

![example](https://user-images.githubusercontent.com/397902/45769694-fbca5600-bc05-11e8-95b9-b0c93bc3abe6.jpg)

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-09-26 19:18 UTC, JaeBea requested changes
@damontgomery ,
I believe the styling should be applied to an `<a>`. Buttons won't navigate to a different page so the use of buttons for the HTML element is flawed to begin with in the style guide. Could you either change the SG2 HTML to use `<a>` and update css accordingly or move the styling that you added to be `button, a` instead of nested?

2018-09-27 15:18 UTC, damontgomery commented
Talking with Beatrice, she explained that the button without an anchor is used in many places right now. Given my shift in focus to personalization. We have decided that it makes the most sense to go with the quick fix (style both the button and anchor the same) and address the use of buttons later.

2018-09-27 16:30 UTC, damontgomery commented
@JaeBea, The way I was able to get this working with https://github.com/AmericanMedicalAssociation/ama-d8/pull/762 was to use only the `a` element with no `button`. I applied the classes for the `button` to the `a` element. That seems to work.

`inline-block` is needed for the `a` element to maintain the spacing within that membership block.

As you mentioned, updating the style guide seems challenging since buttons are used in many different places.

Can you take a look at the two PRs and see if that makes sense or if you have suggestions?

2018-09-27 19:31 UTC, JaeBea approved these changes
@damontgomery ,
This solution works fine. I have tested with D8 and updated the anchors are keeping the style that was originally intended. I will approve and merge into develop.

2018-09-27 19:31 UTC, merged