EWL-6000 theme confirmation page
AmericanMedicalAssociation/ama-style-guide-2 pull request #417
Opened 2018-09-20 21:11 UTC by designerneil

**Jira Ticket**
- [EWL-6000: A1 | Theme webform confirmation pages](https://issues.ama-assn.org/browse/EWL-6000)

## Description
Update CSS for webform confirmation page

## To Test
- [ ] switch your D8 branch to `feature/EWL-6000-theme-confirmation-page`
- `drush cim`
- switch your SG2 branch to `feature/EWL-6000-theme-confirmation-page`
- update your local.yml to use local SG2
- `scripts/build`
- Fill out this form http://ama-one.local/form/mas-membership-registration
- observe the confirmation page is styled 
- [ ] Did you test in IE 11?

## Visual Regressions

n/a

## Relevant Screenshots/GIFs
<img width="1175" alt="screen shot 2018-09-20 at 4 08 51 pm" src="https://user-images.githubusercontent.com/2271747/45847185-d44fb800-bcef-11e8-9420-fb48d1923154.png">

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-09-27 20:07 UTC, JaeBea requested changes
@designerneil ,
There are a couple of changes needed on this PR.
- Please create a page in SG2 showing the confirmation page.
- There is a lot of code that has been deleted from the code base with no explanation. Please review your changes, confirm that they are intended, and explain the reason for the removal as it relates to the confirmation pages.

2018-09-27 20:24 UTC, designerneil commented on styleguide/source/assets/js/webforms.js
> -/**
This contents of this file was deleted because we moved away from manually doing validation. Validation is now being handled via jQuery validate

2018-09-27 20:24 UTC, designerneil commented on styleguide/source/assets/scss/00-base/_forms.scss
> -}
Most of the css here was moved to webform.scss because it was specific to webforms in D8

2018-09-27 20:24 UTC, designerneil commented on styleguide/source/assets/scss/01-atoms/_text-field.scss
> -.ama__label {
These classes were added because D8 webforms adds specific classes when labels are created

2018-09-27 20:24 UTC, designerneil commented on styleguide/source/assets/scss/01-atoms/_select-menu.scss
> +.form-select.error + .ui-selectmenu-button {
This class accounts for the ui select error styling in D8

2018-09-27 20:26 UTC, designerneil commented
@JaeBea you're probably right about creating a specific confirmation page. Which begs for us to make forms in SG2 that match D8 or vice versa. This is something that is outside the scope this PR or story

2018-09-27 20:46 UTC, JaeBea commented
@designerneil ,
The removal of code that you have described does not relate to the confirmation page. Those changes need to be addressed in its own PR.

I am not requesting anything for the individual form samples, but I believe the confirmation page should be added in this PR as the time to do so is so minimal and putting it off is problematic in the long run. Since the JIRA ticket does not state that this must be created and is directed towards d8 specifically, so I will rescind my request for the page to be created in SG2.

Once unrelated changes are removed from the PR I can approve.

2018-09-28 17:55 UTC, designerneil commented
@JaeBea this branch was branched off of https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/418/files

That branch was merged. I have merged develop into this branch. You should only see one file changed

2018-10-02 19:07 UTC, damontgomery reviewed
The test content did not have a title to reference.

2018-10-16 18:14 UTC, JaeBea approved these changes
@designerneil ,
Unrelated changes have disappeared with merge of develop branch. I will approve and merge.

2018-10-16 18:14 UTC, merged