EWL-4434 Updates typography and adds new typography from UX
AmericanMedicalAssociation/ama-style-guide-2 pull request #43
Opened 2018-01-17 16:57 UTC by designerneil

## Ticket(s)

Please do not submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**

- [EWL-4434: SG2 | Update typography and fonts(https://issues.ama-assn.org/browse/EWL-4434)

## Description

Typography accommodate topic page font sizes and styles and new styles and sizes for the new article pages. 

Topic related typography will have a class called topic attached to the body and has topic attached to the header classes i.e. topic__h1, topic__h2, topic__h3

## To Test

- [ ] http://localhost:3000/?p=atoms-headings

## Visual Regressions

Does it match SG1 and the font sizes in guideline attached to this story?

## Relevant Screenshots/GIFs

<img width="725" alt="screen shot 2018-01-17 at 10 56 48 am" src="https://user-images.githubusercontent.com/2271747/35055582-2380e922-fb75-11e7-9576-930e048f1173.png">

## Remaining Tasks

Remaining tasks?

## Additional Notes

Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

2018-01-17 16:58 UTC, designerneil commented on styleguide/source/_meta/_00-head.twig
> -<body class="{{ bodyClass }}">
line break in file but github doesn't see it for some reason

2018-01-17 17:00 UTC, designerneil commented on styleguide/source/assets/scss/00-base/_font-variables.scss
> -);
I don't know why github is asking for a line break here. It's not the EOF

2018-01-18 18:56 UTC, labbydev commented
@designerneil the scss isn't compiling on this right now because of some remaining variables:
```
Error in plugin 'sass'
Message:
    source/assets/scss/00-base/_forms.scss
Error: Undefined variable: "$gray-8".
        on line 58 of source/assets/scss/00-base/_forms.scss
>>     border: 1px solid $gray-8;

   ----------------------^
```
This should be already fixed in the latest `develop` please rebase with `develop` and see if that fixes the issue. Please also let me know specifically what I should be looking for while testing this visually.

2018-01-18 20:09 UTC, labbydev commented
@designerneil I'm still getting the same errors from `_forms.scss`

2018-01-18 20:18 UTC, labbydev requested changes
A couple of quick tweaks to the classes. When making the tweaks you may also need to check that the twig using the classes is up-to-date as well.

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/00-base/_typography.scss
> +}
add empty line

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/00-base/_typography.scss
> +  %topic__type-small {
these should be doubly hyphen before small since it's a modifier (e.g `topic__type--small`)

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/00-base/_typography.scss
> +  %topic__type-italic {
these should be double hyphen before italic since it's a modifier (e.g. `topic__type--italic`)

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/01-atoms/_links.scss
> +.topic__link-black {
doubly hyphen before black

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/01-atoms/_links.scss
> +.topic__link-white {
double hyphen before white

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/01-atoms/_links.scss
> +.topic__link-blue {
double hyphen before blue

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/02-molecules/_ribbon-dropdown.scss
> +  @extend .ama__type-small;
double hyphen before small

2018-01-18 20:18 UTC, labbydev commented on styleguide/source/assets/scss/02-molecules/_ribbon-user-menu.scss
> +  @extend .ama__type-small;
double hyphen before small

2018-01-18 22:54 UTC, chelsiejohnston commented
@designerneil please resolve merge conflicts so this can be re-reviewed

2018-01-19 16:14 UTC, chelsiejohnston commented
The thinner font weights being used for "regular" from the mockup are perhaps too skinny - we'll review with UX later, but merging for now.

2018-01-19 16:14 UTC, merged