Fixes layout for IE11
AmericanMedicalAssociation/ama-style-guide-2 pull request #443
Opened 2018-10-11 21:51 UTC by designerneil

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [Issue XXX: Issue Title](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/XXX)

**Jira Ticket**
- [EWL-XXXX: Ticket Title](https://issues.ama-assn.org/browse/EWL-XXXX)

## Description
Explain the technical implementation of the work done.

## To Test
- [ ] Add detailed steps for reviewers to test this feature.
- [ ] Did you test in IE 11?

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/[PULL_REQUEST_ID]/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-10-16 17:13 UTC, nstriedinger commented
Spacing borked in IE11

![screen shot 2018-10-16 at 1 11 47 pm](https://user-images.githubusercontent.com/231467/47034361-2cd67180-d145-11e8-90d7-a93def5946f6.png)

2018-10-16 19:42 UTC, designerneil commented
<img width="1387" alt="screen shot 2018-10-16 at 2 42 11 pm" src="https://user-images.githubusercontent.com/2271747/47042750-b2f8b500-d151-11e8-8371-43eb77cc1b12.png">

2018-10-17 13:56 UTC, nstriedinger requested changes
see comments

2018-10-17 13:56 UTC, nstriedinger commented on styleguide/source/assets/scss/01-atoms/_image.scss
> +    &--right {;
@designerneil remove semicolon.
```suggestion
    &--right {
```

2018-10-17 14:24 UTC, designerneil commented on styleguide/source/assets/scss/01-atoms/_image.scss
> +    &--right {;
good catch!

2018-10-17 14:54 UTC, nstriedinger approved these changes

2018-10-17 14:54 UTC, merged