EWL-6562 mobile search drawer
AmericanMedicalAssociation/ama-style-guide-2 pull request #520
Opened 2018-11-07 18:43 UTC by designerneil

## JIRA Ticket(s)
- [EWL-6562: Global nav - search component required for mobile](https://issues.ama-assn.org/browse/EWL-6562)

## Description:
Add mobile search drawer

## To Test:
- refer to PR https://github.com/AmericanMedicalAssociation/ama-d8/pull/1032 for testing instructions

## Automated Test:
n/a

## Style Guide:

## Relevant Screenshots/GIFs:
<img width="451" alt="screen shot 2018-11-07 at 12 41 40 pm" src="https://user-images.githubusercontent.com/2271747/48152822-7e78a480-e28a-11e8-9652-8ac19cecc4f4.png">

## Additional Notes:
n/a

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

2018-11-07 21:01 UTC, nstriedinger requested changes
@designerneil Take a look at this stuff

2018-11-07 21:01 UTC, nstriedinger commented on styleguide/source/assets/js/main-navigation.js
> +      $($mobileSearchTrigger).click(function(e) {
```suggestion
      $($mobileSearchTrigger).unbind('click').click(function(e) {
```

2018-11-07 21:01 UTC, nstriedinger commented on styleguide/source/assets/js/main-navigation.js
>          if($('#global-menu').prop('checked')) {
```suggestion
        if ($('#global-menu').prop('checked')) {
```

2018-11-07 21:01 UTC, nstriedinger commented on styleguide/source/assets/js/main-navigation.js
>          } else {
```suggestion
        } 
        else {
```

2018-11-07 21:04 UTC, nstriedinger commented
Some oddities here.
![screen shot 2018-11-07 at 4 02 33 pm](https://user-images.githubusercontent.com/231467/48160797-cefdfb00-e2a6-11e8-9971-58be8904fa14.png)

2018-11-07 21:14 UTC, designerneil commented
@nstriedinger the button staying purple shouldn't be a problem because it's indicating the search drawer is active

2018-11-08 16:22 UTC, damontgomery commented
@nstriedinger, If this is good to merge, can you update your review and remove the `ready for review` labels?

2018-11-09 16:12 UTC, merged