EWL-6638 Updates global submenu to center within the viewport
AmericanMedicalAssociation/ama-style-guide-2 pull request #555
Opened 2018-11-28 17:33 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-6638: High - enhancement - Menu Expansion](https://issues.ama-assn.org/browse/EWL-6638)

## Description
UX has asked that the global menu flyout submenu to be always centered in viewport to display as much info as possible

## To Test
- [ ] switch your SG2 branch to `bugfix/EWL-6638-menu-expansion`
- [ ] `gulp serve`
- [ ] switch your D8 branch to  `bugfix/EWL-6638-menu-expansion`
- [ ] enable local SG2 on your D8 instance
- [ ] `drush @one.local cr`
- [ ] visit http://ama-one.local/
- [ ] click on the hamburger menu in the global header
- [ ] hover over the categories
- [ ] observer the about category submenu is centered
- [ ] resize your viewport to 1440X900
- [ ] click on the hamburger menu again
- [ ] hover over the about category
- [ ] observer the about category submenu is still centered

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bugfix/EWL-6638-menu-expansion/html_report/index.html).

## Relevant Screenshots/GIFs
<img width="1399" alt="screen shot 2018-11-28 at 11 33 20 am" src="https://user-images.githubusercontent.com/2271747/49170512-ec504300-f301-11e8-8712-d47fbcadb432.png">

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2018-11-28 22:27 UTC, nstriedinger commented
@designerneil I'm not seeing this.
![screen shot 2018-11-28 at 5 26 36 pm](https://user-images.githubusercontent.com/231467/49186498-cdb67000-f332-11e8-85dc-73a3018507d3.png)

2018-11-28 22:34 UTC, nstriedinger commented
@designerneil Pardon, you didn't mark this as ready to review. You must still be working on it.

2019-01-03 20:56 UTC, tcfunk requested changes
I'm getting a sort of overlap effect with the foldout menu
![overlap](https://user-images.githubusercontent.com/1919263/50661095-a709db80-0f67-11e9-983b-0ea7afe0447c.png)

2019-01-04 20:21 UTC, tcfunk commented
@designerneil I spoke with Tyler Miller about the error. He said

> that error is just a custom error that Adam created to let him and I know that there's a track analytics event firing that's not accounted for in GTM

so it sounds like they will resolve it from the GTM side later on.

2019-01-04 21:53 UTC, designerneil commented
@tcfunk can you pull SG2 again and make sure it's not cached in your D8 ENV? to confirm it's not cached can you can the color of some random css file perhaps the header background color in assets/03-organisms/_main-navigation.scss?

2019-01-07 19:24 UTC, russom-woldezghi commented
@designerneil I am seeing that the About sub-menu is centered at 1440x900 but when I test other narrower viewports, the About sub-menu is not centered. Look at the screenshots below: 

![screen shot 2019-01-07 at 2 22 31 pm](https://user-images.githubusercontent.com/541745/50788626-f0b83600-1287-11e9-9673-7290c4093e9e.png)
![screen shot 2019-01-07 at 2 22 47 pm](https://user-images.githubusercontent.com/541745/50788627-f0b83600-1287-11e9-8493-55b7e8df21c2.png)

2019-01-07 19:58 UTC, tcfunk requested changes
The submenu is centering properly, but I noticed that the indicator arrows are missing from the primary menu (the arrows that indicate a submenu exists for that item).
![indicator_arrows_missing](https://user-images.githubusercontent.com/1919263/50790362-53a7ce00-1284-11e9-8d27-0fbc518391e9.png)

2019-01-07 20:05 UTC, designerneil commented
@russom-woldezghi the tablet version cannot be centered because there is too much information in the submenu.

2019-01-07 20:06 UTC, designerneil commented
@tcfunk the arrows have been restored

2019-01-07 20:38 UTC, tcfunk approved these changes

2019-01-07 20:55 UTC, merged