Updates cookie and adds js file to Drupal files
AmericanMedicalAssociation/ama-style-guide-2 pull request #587
Opened 2019-02-13 20:33 UTC by designerneil

## JIRA Ticket(s)
- [EWL-6943: Announcement banner (frontend)](https://issues.ama-assn.org/browse/EWL-6943)

## Description:
- Adds `banner` content type.
- Adds `admin/announcement-banner` view page for admins to order multiple banners
- Adds `banner.feature` Behat test to test if users can publish banner, tests if banner is unpublished for users without access to view unpublished banner nodes. 
- Adds `page.banner` variable to `page.html.twig` to render banner node objects - applies to all pages site-wide. 

## To Test:
- In SG2 pull branch `feature/EWL-6771-annoucement-banner`
- `gulp serve`
- D8 switch branch to `feature/EWL-6771-annoucement-banner`
- Enable local SG2 testing your D8
- Pull down branch and import configuration changes: 
  - `drush @one.local cim -y`
  - `drush @one.local cr`
- Add multiple node banners: http://ama-one.local/node/add/banner (create two one published and one unpublished) 
- Navigate to: http://ama-one.local/admin/announcement-banner (notice there will be a Drupal warning message)
- Save order of nodes (place published banner node first)
- Observe that banner is visible to all users. 
- Navigate back to: http://ama-one.local/admin/announcement-banner (notice there will be NO a Drupal warning message)
- Save order of nodes (place unpublished banner node first)
- Observe that banner is NOT visible to `anonymous` users. 

## Relevant Screenshots/GIFs:
![screen shot 2019-02-13 at 2 33 12 pm](https://user-images.githubusercontent.com/2271747/52741982-50e37b80-2f9c-11e9-9bc6-832c438e448b.png)

## Additional Notes:
Anything more to add?

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

2019-02-18 17:41 UTC, russom-woldezghi commented
@designerneil I am not able to see the styling as you specified in the screenshot. I am only getting an unstyled theme of the banner. 

Also, would it be possible to have indicator of sort to show the node is unpublished? In case, a user is reviewing it (before publishing) and forgets to publish the banner node.

2019-02-19 15:24 UTC, russom-woldezghi commented on styleguide/source/assets/js/alert.js
> +       console.log( $.cookie('ama__alert--hide') );
@designerneil Can you remove console.log :) ?

2019-02-19 15:26 UTC, russom-woldezghi requested changes
Just a minor feedback, looks good otherwise.

2019-02-21 16:29 UTC, designerneil commented
@russom-woldezghi thanks. Good catch. The console.log has been removed

2019-02-26 20:50 UTC, russom-woldezghi approved these changes

2019-02-27 21:52 UTC, merged