Updates main navigation to scroll when it doesn’t fit inside the view…
AmericanMedicalAssociation/ama-style-guide-2 pull request #601
Opened 2019-03-08 16:40 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-6638: High - enhancement - Menu Expansion](https://issues.ama-assn.org/browse/EWL-6638)

## Description
When the main navigation drop down doesn't the viewport a user should be able to scroll the main navigation and see the rest of the navigation links. If the flyout content doesn't fit within the viewport a user should be able able to scroll and see the rest of it.

## To Test
- [x] switch branch to `feature/EWL-6638-menu-expansion`
- [x] run `gulp serve`
- [x] navigate to pages > press-release
- [ ] resize browser viewport so not all the main navigation drop fits within it
- [ ] observe how you are able to scroll the main purple drop down navigation
- [ ] resize the viewport so it accomodates all of the main dropdown navigation content
- [ ] observe how the scrolling functionality disappears because it's not needed anymore
- [ ] hover over the category links in the purple main navigation dropdown
- [ ] observe how a user is able to scroll if it doesn't all fit in the viewport''
- [x] Did you test in IE 11?

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-6638-menu-expansionv/html_report/index.html).

## Relevant Screenshots/GIFs

## Remaining Tasks
Test in D8 

## Additional Notes
This PR is related to a PR in D8 `feature/EWL-6638-menu-expansion`

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-03-13 19:42 UTC, JaeBea commented
@designerneil ,
Please update description with details of work performed and ticket title/link with the one for this work.

2019-03-14 17:24 UTC, designerneil commented
@JaeBea thanks. I must have copied another PR by accident into this one.

2019-03-19 18:58 UTC, JaeBea requested changes
@designerneil ,
The dark purple panel scrolls fine but the other two panels do not. The white panel, the one with the subcategories, does not scroll unless I grab the scroll bar and drag it. The grey panel, the one with news articles stubs, does not even have a scroll. The white panel also does not show the homepagePurple panel title.

I have listed other code feedback below.

2019-03-19 18:58 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +      var $categoryNavMenuMResizedHeight = 0;
The `$` vars dictate a jQuery object. `$categoryNavMenuResizedHeight`, `$categoryNavMenuHeight`, and `$viewportHeight` are not jQuery objects, just ints. Please update the variable names.

2019-03-19 18:58 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +
Remove extra line.

2019-03-19 18:58 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +
Remove extra lines.

2019-03-19 18:58 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +      function categoryNavHeight($resizeViewportHeight) {
All variables in this function, save `$categoryNavWrapper`, hold integers. They should not have `$` in front of their names. Please update.

2019-03-19 18:58 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +        $viewportHeight = typeof $resizeViewportHeight !== 'undefined' ? $resizeViewportHeight : $(window).innerHeight();
This is not easy to scan, mostly because it isn't a simple truthy statement. Can this be updated to more readable?

2019-03-20 17:15 UTC, designerneil commented
@JaeBea take a look again at the submenus they should scroll using the trackpad and mouse.

2019-04-26 15:14 UTC, JaeBea commented on styleguide/source/assets/js/main-navigation.js
> +          $productNavHeight = 0,
Please update this to be `productNavHeight`. It is not a jQuery object.

2019-04-26 15:36 UTC, JaeBea requested changes
@designerneil ,
There is an issue with the white menu panel scroll. It scrolls both the white panel and the article stubs in the grey panel when it should only scroll white panel. I have attached two screenshots of before and after scrolling.
Before scroll:
![image](https://user-images.githubusercontent.com/4438120/56819249-f58cff80-680e-11e9-8595-68bdb483c975.png)
After scroll:
![image](https://user-images.githubusercontent.com/4438120/56819289-05a4df00-680f-11e9-8926-7b9aa0918dd3.png)


The category label is showing a regression as well. It is now black instead of bright purple and all uppercase text.

2019-04-29 15:03 UTC, merged