EWL-7013: Added submit event button and Ama event banner
AmericanMedicalAssociation/ama-style-guide-2 pull request #606
Opened 2019-03-12 16:45 UTC by mgrahamama

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
N/A

**Jira Ticket**
- [EWL-7013: Ticket Title](https://issues.ama-assn.org/browse/EWL-7013)

## Description
"Submit an event" button added, as well as an "AMA Event" banner added to events that are hosted by AMA. There were a few formatting issues that differed from the wireframes that i fixed:
- No padding above title container
- Event img, title, date were not aligned properly, as well as incorrect padding. I also removed the hr tag and used css to add a border to the container.

## To Test
- [ ] cd to styleguide and run gulp serve.
- [ ] navigate to the event listing page: http://localhost:3000/patterns/05-pages-event-listing/05-pages-event-listing.html
- [ ] Check for Submit an event button and AMA Event banner
- [ ] Did you test in IE 11, FF, Chrome?
- [ ] Did you test on smaller screen sizes?

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-7013-SG2-Event-Listing-External-Event-Enhancement/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Before:
![screencapture-americanmedicalassociation-github-io-ama-style-guide-2-patterns-05-pages-event-listing-05-pages-event-listing-html-2019-03-12-11_28_16](https://user-images.githubusercontent.com/47533659/54217649-09c4a980-44ba-11e9-96d1-43ee8f94a78d.png)

After: 
![screencapture-localhost-3000-patterns-05-pages-event-listing-05-pages-event-listing-html-2019-03-12-11_12_18](https://user-images.githubusercontent.com/47533659/54216511-c9fcc280-44b7-11e9-9a3d-f1231914c5a8.png)

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-03-14 19:34 UTC, designerneil commented on styleguide/source/assets/scss/03-organisms/_masthead.scss
> +      display: -webkit-box;
Remove vendor prefixes. We use auto-prefixer. You can just put display: flex

2019-03-14 19:34 UTC, designerneil commented on styleguide/source/assets/scss/02-molecules/_event-stub.scss
> +    margin-bottom: 10px;
Use 
`
@include gutter($margin-bottom-half...);
width: 100%;
min-width: 180px;
height: auto;
`

2019-03-14 19:34 UTC, designerneil commented on styleguide/source/assets/scss/02-molecules/_event-stub.scss
> +    margin-bottom: $gutter-mobile/2;
`
@include gutter($margin-bottom / 2);
@include gutter($padding-top-quarter / 2);
@include gutter($padding-bottom-quarter.);
@include gutter($padding-left-half);
background-color: $purple;
width: 180px; 
color: $white;
`

2019-03-14 19:34 UTC, designerneil commented
In general we should not hard code values in our CSS

2019-03-14 19:35 UTC, designerneil commented
@mgrahamama good job on this PR it works as described. Just some stylistic changes are needed. Thanks

2019-03-15 21:03 UTC, designerneil requested changes

2019-03-15 21:03 UTC, designerneil commented on styleguide/source/assets/scss/02-molecules/_event-stub.scss
> +  border-bottom: 1px solid #7F7F7F;
remove hard code value here

2019-03-15 21:03 UTC, designerneil commented on styleguide/source/assets/scss/02-molecules/_event-stub.scss
> +    @include gutter($margin-bottom-full...);
All `@includes` need to be the first value

@include gutter($margin-bottom-full...);
width: 100%;
min-width: 180px;
height: auto;

2019-03-15 21:03 UTC, designerneil commented on styleguide/source/assets/scss/03-organisms/_masthead.scss
> +    &__title {
Need spaces between classes

2019-03-15 21:04 UTC, designerneil commented
BTW sorry for being especially hard on this PR. I'm using it as a tool to show you our process. Thanks for bearing with me.

2019-03-15 21:07 UTC, mgrahamama commented
> BTW sorry for being especially hard on this PR. I'm using it as a tool to show you our process. Thanks for bearing with me.

@designerneil not a problem at all, i appreciate the details. i want to make sure i follow the conventions correctly

2019-03-18 14:30 UTC, designerneil approved these changes

2019-03-18 14:30 UTC, merged