EWL-6638 - High - enhancement - Menu Expansion
AmericanMedicalAssociation/ama-style-guide-2 pull request #623
Opened 2019-04-29 17:17 UTC by designerneil

## Ticket(s)

**Jira Ticket**
- [EWL-6638: High - enhancement - Menu Expansion](https://issues.ama-assn.org/browse/EWL-6638)

## Description
Fixes width of the flyout menu which causes wrapping of content. 
Fixes category header color

## To Test
- [ ] switch your SG2 branch to [feature/EWL-6638-menu-expansion](https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/601)
- [ ] run `gulp serve`
- [ ] visit http://localhost:3000/?p=pages-homepage
- [ ] click on the header hamburger menu
- [ ] hover over the categories
- [ ] observe how the flyout content no longer wraps
- [ ] observe the category link color is now purple
- [ ] Did you test in IE 11?

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/fature/EWL-6638-menu-expansion?expand=1/html_report/index.html).

## Relevant Screenshots/GIFs
![screen shot 2019-03-08 at 10 40 24 am](https://user-images.githubusercontent.com/2271747/54041966-ade2e380-418e-11e9-8c6b-b74e58d079f8.png)

## Remaining Tasks
Test in D8 

## Additional Notes
This PR is related to a PR in D8 `feature/EWL-6638-menu-expansion`

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-04-29 18:39 UTC, tcfunk requested changes
~I am able to scroll the nav on mobile, but if it is cut off on desktop I am not able to scroll to view the rest of the nav. For reference, I tested at **1366x768** (reportedly the most common desktop resolution).~

Sorry I must have had some caching going on. It is scrolling.

2019-04-29 18:47 UTC, tcfunk approved these changes

2019-04-29 19:28 UTC, JaeBea requested changes
@designerneil,
The only thing I see is that the scrollbar is out further right than the content. @tcfunk are you getting the same thing? The scroll bar may look out of place regardless as it will be longer than the content next to it, but it looks as iff something went wrong.

<img width="1360" alt="Screen Shot 2019-04-29 at 2 22 08 PM" src="https://user-images.githubusercontent.com/4438120/56921104-86234400-6a8a-11e9-8a86-cbb67b0a98f3.png">

2019-04-29 19:53 UTC, designerneil commented
@JaeBea we will have to showcase the scrollbar functionality to a PM before release for sure

2019-04-30 15:52 UTC, JaeBea approved these changes
@designerneil ,
I have created ticket [EWL-7176 Remove Menu Expansion Scroll Bars](https://issues.ama-assn.org/browse/EWL-7176) to address the scrollbar on Firefox. I will approve this and then merge into develop once Travis finishes.

2019-04-30 15:52 UTC, merged