EWL-6775 Social Sharing Icons - sticky
AmericanMedicalAssociation/ama-style-guide-2 pull request #624
Opened 2019-04-29 19:23 UTC by designerneil

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**
- [EWL-6775: Social Sharing Icons - sticky](https://issues.ama-assn.org/browse/EWL-6775)

## Description
Explain the technical implementation of the work done.

## To Test
- [ ] switch your SG2 branch to `feature/EWL-6955-sticky-social-icons`
- [ ] run `gulp serve`
- [ ] visit http://localhost:3000/?p=pages-event
- [ ] scroll page
- [ ] observe the social icons move to the left of the article and remained fixed
- [ ] enable local SG2 for your D8 environment
- [ ] visit any interior page with social icons
- [ ] scroll page
- [ ] observe how the social icons move to the left of the article and stays pinned
- [ ] Did you test in IE 11?

## Visual Regressions

## Relevant Screenshots/GIFs
![Screen Shot 2019-04-29 at 2 23 05 PM](https://user-images.githubusercontent.com/2271747/56921005-52481e80-6a8a-11e9-8f5f-4f5ae824f99e.png)

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-04-29 20:11 UTC, JaeBea requested changes
@designerneil,
I see two issues. 
1. The icons go into the footer when scrolling instead of disappearing.
<img width="704" alt="Screen Shot 2019-04-29 at 3 07 42 PM" src="https://user-images.githubusercontent.com/4438120/56923706-d8676380-6a90-11e9-9ea0-a728c23febb6.png">

2. The icons should only stick to the side of the window only when there is enough space that they do not overlap content. 
<img width="1211" alt="Screen Shot 2019-04-29 at 2 53 41 PM" src="https://user-images.githubusercontent.com/4438120/56923803-119fd380-6a91-11e9-893d-42ebb964b432.png">

2019-04-29 22:33 UTC, designerneil commented
@JaeBea the overlaps have been addressed

2019-04-30 16:27 UTC, JaeBea requested changes
@designerneil ,

The two issues I saw have been resolved, but another issue has been introduced. The logic for ensuring the social icons do not go into the footer area is preventing social icons from going sticky if the footer height plus vertical social icon height is larger than the height of the viewport, regardless of if the footer is in view at the time. Please update so that the icons will still be sticky until the footer is in the viewport and then remove the sticky functionality.

2019-04-30 19:38 UTC, designerneil commented
@JaeBea the scroll event is active while scrolling and the social icons cannot be hidden or shown until the event has finished. Therefore, when the page is being scrolled the social icons will not hide until the scroll event has completed which will then have them running into the footer. 

Instead of this bad user experience I've implemented a conditional that will hide the social icons if the viewport height is less than 745 on scroll. This will hide the social icons temporarily until the user has finished scrolling. This conditional will prevent the user from having the social icons overlapping the footer.

2019-05-06 16:28 UTC, JaeBea requested changes
@designerneil ,
There is only one remaining issue here. On shorter screens (my laptop with room for the dock) the social share icons disappear and never come back until the screen is reloaded. Taller screens this is not an issue. After this is fixed, this should be good to merge.

2019-05-06 18:11 UTC, designerneil commented
@JaeBea the sticky social navs disappearing on smaller screens has been addressed.

2019-05-06 19:03 UTC, JaeBea approved these changes
@designerneil ,
My feedback has been addressed. I will approve and merge into develop.

2019-05-06 19:03 UTC, merged