EWL-7269: Evergreen Pages | Embedded image caption does not wrap
AmericanMedicalAssociation/ama-style-guide-2 pull request #640
Opened 2019-05-29 21:03 UTC by caharder

## Ticket(s)

**Jira Ticket**
- [EWL-7269: Evergreen Pages | Embedded image caption does not wrap](https://issues.ama-assn.org/browse/EWL-7269)

## Description
Added CSS to wrap caption on embedded images.

## To Test
- [ ] Pull SG branch /feature/EWL-7222-centered-masthead
- [ ] Pull AMAONE branch /feature/EWL-7211-EP-Twig-Template-Page
- [ ] run gulp serve
- [ ] Enable local SG2 in your local.yml in D8
- [ ] run drush @one.local cr
- [ ] Import config
- [ ] Create a new Evergreen page
- [ ] Add an Evergreen tab
- [ ] Add a wysiwyg paragraph in the evergreen tab
- [ ] Add text and embed an image (thumbnail) in the wysiwyg with a long caption
- [ ] Save and verify that the text of the caption is wrapping

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
<img width="404" alt="Screen Shot 2019-05-29 at 4 02 37 PM" src="https://user-images.githubusercontent.com/43501792/58591154-412a3300-822b-11e9-8225-a8b6d3de4e76.png">

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-05-31 15:47 UTC, designerneil submitted a review, later dismissed
<img width="1232" alt="thumbnail" src="https://user-images.githubusercontent.com/2271747/58717689-6769e300-8391-11e9-8e6a-f20f77213f9c.png">

2019-05-31 20:41 UTC, caharder commented
**Tabs are not lining up but wrapping**
This is happening because the tabs names are too long to fit on one line. If you entered shorter tab names, they will line up. The right sidebar prevents them from spanning the entire page.

**Text is not wrapping around thumbnail**
It looks like the image was added at the bottom of the text, if the image is moved up in the wysiwyg, the text should wrap.

**The thumbnail is in the wrong place by default with alignment none**
This has been corrected in [PR-1427](https://github.com/AmericanMedicalAssociation/ama-d8/pull/1427). I had to edit a module that was making all embedded images align right. Now these images should follow the alignment given, but other embedded images will still automatically align right.

**Caption is getting truncated**
There is a character limit for captions. You will notice it is also truncated when entered.

2019-05-31 21:21 UTC, tcfunk submitted a review, later dismissed
Looks great!

2019-05-31 21:33 UTC, tcfunk requested changes
Everything looks good except @designerneil pointed out to me that extremely long tab names cause the tabs to stack (like in his screenshot). He mentioned maybe forcing a max width on the tab and letting the text inside it wrap.

I think this is a question to bring up with a PM though, just to make sure that it's an acceptable thing to do based on designs or whatever.

2019-06-03 15:11 UTC, caharder commented
@tcfunk Carlos said we can bring the wrapping tabs up to UX after release.

2019-06-03 15:28 UTC, tcfunk approved these changes
Requested changes to be addressed in a later PR 👍

2019-06-03 15:28 UTC, merged