EWL-6782: Adding Correct Rule to Properly Display Blockquote before to the left
AmericanMedicalAssociation/ama-style-guide-2 pull request #691
Opened 2019-10-29 00:27 UTC by acidaniel

## Ticket(s)

**Jira Ticket**
- [EWL-6782: Formatting blockquotes](https://issues.ama-assn.org/browse/EWL-6782)

## Description
Adding rule to display properly blockquote `before` to the left

## To Test
* Add a Blockquote throught the ckeditor
* Ensure it is displaying correctly on the ckeditor and when save content it is displaying correctly according the Zeplin designs.

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
This PR depends as well of the [PR 1653](https://github.com/AmericanMedicalAssociation/ama-d8/pull/1653)

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2019-10-29 14:38 UTC, russom-woldezghi commented
I think the Zeplin design needs the purple bar more flush (shift to the left). I think removing the `<blockquote>` attribute `margin-left: 9.2%;` helps with that. See screenshot below: 

<img width="446" alt="Screen Shot 2019-10-29 at 10 30 11 AM" src="https://user-images.githubusercontent.com/541745/67777424-16d9dd00-fa38-11e9-8909-0e6fb5989dfc.png">
<img width="311" alt="Screen Shot 2019-10-29 at 10 30 16 AM" src="https://user-images.githubusercontent.com/541745/67777425-16d9dd00-fa38-11e9-940f-f25b478d03b6.png">


On Zeplin: 

<img width="368" alt="Screen Shot 2019-10-29 at 10 33 39 AM" src="https://user-images.githubusercontent.com/541745/67777439-1e00eb00-fa38-11e9-81f5-d5dccd54edd7.png">

Link to zeplin: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5c925aa64e90c024d1ca0a1d (mobile)
https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5c925aa669aa0a0575d41c6b (tablet)
https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5c925aa6bbd849067f25bb4d (desktop)

2019-10-29 16:44 UTC, acidaniel commented
@russom-woldezghi  You were right I just removed that property.

2019-10-29 16:59 UTC, russom-woldezghi commented
Looks good. Thanks for making the change.

2019-10-29 16:59 UTC, russom-woldezghi approved these changes

2019-10-29 19:19 UTC, joshuathorne requested changes
Still seeing significant display issues. Holding ticket.
![Screen Shot 2019-10-29 at 2 18 26 PM](https://user-images.githubusercontent.com/10862145/67801376-0d13a200-fa57-11e9-9ed3-f8e03d1b29f8.png)

2019-10-30 21:31 UTC, acidaniel commented
@Dr-Zee Can you please post an example link in order to see the issues you found, and also @ccuiriz  I believe we might need to define the scope of this blockquote, since in the designs the blockquote is coming only with text and text with links.

2019-11-04 20:57 UTC, closed without merging