EWL-7884: Forums listing element in SG2
AmericanMedicalAssociation/ama-style-guide-2 pull request #778
Opened 2020-03-05 17:22 UTC by plibby-ama

## Ticket(s)

**Github Issue**
- N/A

**Jira Ticket**
- [EWL-7884: Forums listing element in SG2](https://issues.ama-assn.org/browse/EWL-7884)

## Description
Created new element for forums listing element.

## To Test
- [ ] Pull branch
- [ ] Run gulp serve
- [ ] Verify the following elements match the zeplin:
   http://localhost:3000/?p=molecules-forum-listing

Zeplin:
https://app.zeplin.io/project/5e56f2d8a3e66965c0092ba0/screen/5e56f3228d27f0666e6e5235

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/[PULL_REQUEST_ID]/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2020-03-05 19:49 UTC, caharder requested changes
Center the topics and posts, but not last post
![Pattern_Lab_-_molecules-forum-listing](https://user-images.githubusercontent.com/43501792/76019627-a3654200-5ee7-11ea-9ab8-1622a67604e1.png)

Add space here:
![Pattern_Lab_-_molecules-forum-listing](https://user-images.githubusercontent.com/43501792/76019861-06ef6f80-5ee8-11ea-9eb6-c23a6c8c40ae.png)

Also, remove the header, we will need to build that into an organism or template.

2020-03-05 19:49 UTC, caharder commented on styleguide/source/assets/scss/02-molecules/_forum-list.scss
> +        font-size: 22px;
Add font-weight to forum title
a {
  font-weight: 600;
}

2020-03-05 19:49 UTC, caharder commented on styleguide/source/assets/scss/02-molecules/_forum-list.scss
> +        margin-left: 2em;
Add font-weight to forum listings
a {
  font-weight: 600;
}

2020-03-05 21:37 UTC, plibby-ama commented
> Center the topics and posts, but not last post
> ![Pattern_Lab_-_molecules-forum-listing](https://user-images.githubusercontent.com/43501792/76019627-a3654200-5ee7-11ea-9ab8-1622a67604e1.png)
> 
> Add space here:
> ![Pattern_Lab_-_molecules-forum-listing](https://user-images.githubusercontent.com/43501792/76019861-06ef6f80-5ee8-11ea-9eb6-c23a6c8c40ae.png)
> 
> Also, remove the header, we will need to build that into an organism or template.

Addressed.

2020-03-06 17:51 UTC, caharder requested changes
One more thing. We do need the Posts and Topics centered in this.

Can you add something like this?
`.ama__forum-table-wrap table tr [data-th="Topics"], .ama__forum-table-wrap table tr [data-th="Posts"] {
    text-align: center;
}`

2020-03-06 19:30 UTC, plibby-ama commented
> One more thing. We do need the Posts and Topics centered in this.
> 
> Can you add something like this?
> `.ama__forum-table-wrap table tr [data-th="Topics"], .ama__forum-table-wrap table tr [data-th="Posts"] { text-align: center; }`

This is included now. I had made these changes in the feature/EWL-7868-Create-template-for-the-forum-page-in-SG2 branch so I just merged that here.

2020-03-06 20:36 UTC, caharder approved these changes
Great!

2020-03-06 20:36 UTC, merged