EWL-7885: Attach the new Forum listing style to Drupal
AmericanMedicalAssociation/ama-style-guide-2 pull request #786
Opened 2020-03-11 20:18 UTC by plibby-ama

## Ticket(s)

**Github Issue**
N/A

**Jira Ticket**
- [EWL-7885: Attach the new Forum listing style to Drupal](https://issues.ama-assn.org/browse/EWL-7885)

## Description
CSS tweaks to further align Zeplin designs and original SG2 elements for forum list and forum listing elements.

## To Test
- [ ] Pull branch
- [ ] Pull accompanying D8 branch: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1896
- [ ] Verify that styling on Topic pages (Ex. http://ama-one.local/forums/house-delegates/reference-committee-j/resolutions?sort=desc&order=Resolution) matches Zeplin

**Zeplin**
https://app.zeplin.io/project/5e56f2d8a3e66965c0092ba0/screen/5e56f41443eadc665760d29c

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2020-03-11 20:33 UTC, joshuathorne requested changes
A few issues.

- The `add new forum topic` link needs updated to `start a new topic`
- link needs `ama__button--secondary` class + additional padding + hide list bullet.
- Headings need to be black instead of blue.
- Border surrounding table should be removed.
- There's no zeplin for mobile, but take a look and see if you can cut down on the horizontal space.
- Under "last reply" text is not wrapping well. should probably wrap immediately after username.
- Related to above, username should be replaced by first and last name display.
- Carat after Resolution header is out of alignment.
- print link should be purple, should say "print forum" and have the print icon (these can be found in my current SG PR)
- borders under topics should be darker.
- final topic should have no bottom border.

2020-03-12 19:06 UTC, plibby-ama commented
> A few issues.
> 
>     * The `add new forum topic` link needs updated to `start a new topic`
> 
>     * link needs `ama__button--secondary` class + additional padding + hide list bullet.
> 
>     * Headings need to be black instead of blue.
> 
>     * Border surrounding table should be removed.
> 
>     * There's no zeplin for mobile, but take a look and see if you can cut down on the horizontal space.
> 
>     * Under "last reply" text is not wrapping well. should probably wrap immediately after username.
> 
>     * Related to above, username should be replaced by first and last name display.
> 
>     * Carat after Resolution header is out of alignment.
> 
>     * print link should be purple, should say "print forum" and have the print icon (these can be found in my current SG PR)
> 
>     * borders under topics should be darker.
> 
>     * final topic should have no bottom border.

These have been addressed and ready for re-review.

2020-03-12 19:21 UTC, joshuathorne requested changes
Looking good. A few things.
http://ama-one.local/forums/house-delegates/reference-committee-j/resolutions

- The outer border should be removed from the table.
- the grey header BG should be white
- the values in the resolution and reply columns should be centered
- the borders under each topic should be darker and there should be no border under the last item.
- "Topic" should say "Topics"
- "start a new topic" button needs more LR padding.
- Print link currently has name of forum, should just be "print forum"
http://ama-one.local/forums/house-delegates
- header should say Forums and page header should be the forum title
- same border notes as above.

2020-03-12 22:06 UTC, joshuathorne approved these changes

2020-03-12 22:06 UTC, merged