EWL-8108: Fixing Extra space topic terms and tools and resources.
AmericanMedicalAssociation/ama-style-guide-2 pull request #846
Opened 2020-07-06 18:32 UTC by acidaniel

## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**
- [EWL-8108: Article Page Redesign - Topic Terms](https://issues.ama-assn.org/browse/EWL-8108)

## Description
* Removing not needed space in Tags component

## To Test
- [ ] Compile assets `gulp serve`
- [ ] Clear Cache `drush @one.local cr`
- [ ] Go to a page that contains tags like `http://ama-one.local/residents-students/residency/without-travel-costs-residency-interviews-decline-sharply`
- [ ] Ensure that space between tags and tools and resources block are the same that the one specified in the designs.

## Visual Regressions

N/A

## Relevant Screenshots/GIFs
![Screen Shot 2020-07-06 at 1 24 25 PM](https://user-images.githubusercontent.com/5325044/86626967-1dd4ca00-bf8d-11ea-9266-29d376c3ba1b.png)
![Screen Shot 2020-07-06 at 1 24 04 PM](https://user-images.githubusercontent.com/5325044/86626975-1f9e8d80-bf8d-11ea-93fe-867d7fd0654c.png)
![Screen Shot 2020-07-06 at 1 17 37 PM](https://user-images.githubusercontent.com/5325044/86626980-20372400-bf8d-11ea-926f-0dd929bef2ea.png)

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

2020-07-09 19:19 UTC, caharder requested changes
This ticket is for the spacing below the topic terms. It seems to still be too large. It should be 28px. Also, it looks like you increased the vertical spacing between the two rows of topic terms. The spacing between the topic term buttons should be 14px.

2020-07-13 23:05 UTC, acidaniel commented
@caharder Just fixed the issues above and also fixed breakpoint issues. Thanks

2020-07-16 16:27 UTC, joshuathorne approved these changes

2020-07-16 19:06 UTC, caharder approved these changes

2020-07-16 19:06 UTC, merged